# Site settings
author: Andrew Davisson
title: Andrew's Flatiron Blog
header-img: img/home-bg.png
email: akdavisson4@gmail.com
copyright_name: Andrew Davisson
description: > # this means to ignore newlines until "baseurl:"
  Andrew's Flatiron Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  adavisson

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
